// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/rwlist/rwcore/conf"
	"github.com/rwlist/rwcore/srv"
)

import (
	_ "github.com/rwlist/rwcore/app/resp"
)

// Injectors from wire.go:

func Initialize(filepath string) (Bootstrap, error) {
	config, err := conf.New(filepath)
	if err != nil {
		return Bootstrap{}, err
	}
	srvConfig := conf.ProvideSrv(config)
	server := srv.New(srvConfig)
	bootstrap := Bootstrap{
		Server: server,
	}
	return bootstrap, nil
}
